### ISSUE TITLE
Support __version__ route on web app

### ISSUE THREAD

**Issue by ckolos** [mozilla-services/location-leaderboard#185]
Should return version information in the following format:

{
  "commit": "<commit for this release>",
  "tag": "<code tag>",
  "version": "<code version>",
  "source": "<github url>"
}

**Comment by jaredkerim** [comment]
@ckolos The containing runtime environment should expose the following environment variables:

GIT_COMMIT
GIT_TAG
GIT_VERSION
GIT_SOURCE

which the code will retrieve from the environment at startup time and return.

**Comment by jaredkerim** [comment]
Reopening, this should be implemented as follows:

1) gut out the current __version__ infrastructure

2) add a shell script that inspects the containing git environment and spits out a json file in the following format:

{
	“source”: “URL for the source repository”,
	“version”: “human readable version string”,
	“commit”: “commit hash”
}

3) add an endpoint that looks into the local project root for a version.json file and statically hosts it

4) add a step to teh docker build stage that invokes that script so that a built container contains that file
